#!/bin/bash

echo "                                                                                                   "
echo "███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗     ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗██████╗ "
echo "████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝    ██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗"
echo "██╔████╔██║███████║██║  ███╗██║██║         ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██████╔╝"
echo "██║╚██╔╝██║██╔══██║██║   ██║██║██║         ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗"
echo "██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗    ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║  ██║"
echo "                                                                                                   "
echo "                                                                                                   "
echo "          _____ _          _                     ____                       _ _         "
echo "         |  ___(_)_ __ ___| | ___   ___  _ __   / ___|  ___  ___ _   _ _ __(_) |_ _   _ "
echo "         | |_  | | '__/ _ \ |/ _ \ / _ \| '_ \  \___ \ / _ \/ __| | | | '__| | __| | | |"
echo "         |  _| | | | |  __/ | (_) | (_) | |_) |  ___) |  __/ (__| |_| | |  | | |_| |_| |"
echo "         |_|   |_|_|  \___|_|\___/ \___/| .__/  |____/ \___|\___|\__,_|_|  |_|\__|\__, |"
echo "                                        |_|                                       |___/ "
echo "                                                                                        "
echo "Developed by: Mohammed Abbas..."
echo "______________________________________________________________________________________________________"
echo ""
echo ""
echo ""
echo "Hey when Magic cracker is here, why you fear !!! Well jokes apart, Magic Cracker cracks and find the password using brute force technique with a Magic wordlist,"
echo ""
echo "Yes with a Magic wordlist which will never consume your memory. Passwords will be generated and brute force will be performed on fly."
echo ""
echo "And you know what, No matter whether you have gathered information about your victim or not Magic Cracker will find your victim's password,"
echo ""
echo "even If u failed in cracking the password by using dictionary attacks and with various attacks again don't worry Nerd Magic Cracker will find your victim's password."
echo ""
echo "The Success rate of this Tool is 110%.  It's performance is literally beyond your Imagination,"
echo ""
echo 'The one and only request from Abbas is "KEEP PATIENCE, YOU WILL GET WHAT YOU DESERVE..." '
echo ""
echo ""
echo ""
echo "Let me explain briefly about each options available in 'Magic Cracker', by the way using Magic Cracker is damn easy like eating a cupcake"
echo ""
echo "  Option 1 will perform bruteforce attack to crack Wi-Fi Passwords using CPU, to perform this attack, Attacker should have collected the handshake file of extention .cap"
echo ""
echo "  To Perform this attack either enter 1 or wifi1"
echo ""
echo "  It's damn easy as I said right ?"
echo ""
echo ""
echo "  Now this one is my favourite, Option 2 will perform bruteforce attack to crack Wi-Fi Passwords using GPU, to perform this attack, Attacker should have collected the handshake file of extention .cap"
echo ""
echo "  and convert the collect .cap handshake file to .hccapx. You can convert your .cap file into hccapx from this site https://hashcat.net/cap2hccapx/"
echo ""
echo "  To Perform this attack either enter 2 or wifi2"
echo ""
echo "  If you are lazy like me, then you also will love using option 2, because it's damn fast"
echo ""
echo ""
echo "  Well, option 3 is specially made for people like me, who use different tools for different purpose ;)"
echo ""
echo "  By the way, you are better than me, I'm just a beginner :)"
echo ""
echo "Examples to use custom option:-"
echo ""
echo ""
echo "      You can use aircrack-ng tool without using wordlist in this way,"
echo ""
echo "      aircrack-ng test-01.cap -e Fireloop_Security -w-"
echo ""
echo "  usually as per syntax beside -w we will use wordlist right ? but while using custom option  keep in mind you should use dash  without quotes '-' exactly like this -w- and not like this [-w - or -w'-' or -w '-']"
echo ""
echo "  In some tools to add a  wordlist, as per syntax, Arguement is not required (-a, --a -w --wordlist and etc are called arguement)"
echo ""
echo "  in such cases just enter dash without quotes '-'. Exactly like this - and not like this '-'"
echo ""
echo "  To perform custom attacks either enter 3 or custom"
echo ""
echo ""
echo "  Next option is option 4, I think even Noobs know what is option 4"
echo ""
echo "  Asusual, To open manual page either enter 4 or help"
echo ""
echo "  Last option and I'll say this is the least option. To close the Program either enter 5 or enter exit"
echo ""
echo "  Thanks for your precious time..."
echo ""
echo "      Happy Hacking..."